[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build]
  publish = "dist/"
  base = "crmwebtest"  # Add the correct base path for your app's location

[context.production]
  publish = "dist/"
  command = "ng build CRM.Customer --configuration production"

[context.deploy-preview]
  publish = "dist/"
  command = "ng build CRM.Customer --configuration preview"  # Optional preview config if needed
