[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist/"
  base = "crmwebtest"  # Ensure this is the correct folder name for your app

[context.production]
  command = "ng build CRM.Customer --configuration production"

[context.deploy-preview]
  command = "ng build CRM.Customer --configuration preview"  # Optional preview config if needed
