export const environment = {
  production: true,
  apiIdentityUrl: 'https://identityapi.diamanto.co/api/',
  apiBackOfficeFileUploadUrl: 'https://fileapi.diamanto.co/api/',
  apiFrontOfficeFileUploadUrl: 'https://fileapi.diamanto.co/api/',
  apiFileUploadUrl: 'https://fileapi.diamanto.co/api/',
  apiPricingUrl: 'http://27.109.6.22:9897/api/',
  invStoneArrowBlackImageUrl: '/Arrow_Black_BG.jpg',
  invStoneHeartBlackImageUrl: '/Heart_Black_BG.jpg',
  invStoneAsetWhiteImageUrl: '/Aset_white_bg.jpg',
  invStoneIdealWhiteImageUrl: '/ideal_white_bg.jpg',
  invStoneOfficeLightBlackImageUrl: '/office_light_black_bg.jpg',

  imageURL:"https://diamdna.azureedge.net/imaged/{stoneId}/still.jpg",
  videoURL:"https://diamdna.azureedge.net/Vision360.html?d={stoneId}&sr=-30&s=30",
  nVideoURL:"https://diamdna.azureedge.net/imaged/{stoneId}/{stoneId}.html",
  certiURL:"https://diamdna.azureedge.net/reports/{certiNo}.pdf#zoom=150",
  otherImageBaseURL:"https://diamdna.azureedge.net/imaged/{stoneId}",

  notificationSocketUrl: 'wss://notificationapi.diamanto.co/',
  notificationBaseUrl: 'https://notificationapi.diamanto.co/',
  proposalUrl: 'https://diamanto.co/',
  backOffliceBaseUrl: "http://localhost:25264/api/",
  frontOfficeBaseUrl: "https://frontofficeapi.diamanto.co/",
};