export class LabResult {
    LabName!: string
    jobNo!: string
    controlNo!: string
    diamondDossier!: string
    reportNo!: string
    reportDt!: string
    clientRef!: string
    memoNo!: string
    shape!: string
    length!: string
    width!: string
    depth!: string
    weight!: string
    color!: string
    colorDescriptions!: string
    clarity!: string
    clarityStatus!: string
    finalCut!: string
    polish!: string
    symmetry!: string
    fluorescenceIntensity!: string
    fluorescenceColor!: string
    minGirdle!: string
    maxGirdle!: string
    girdleCondition!: string
    culetSize!: string
    depthPer!: string
    tablePer!: string
    crnAg!: string
    crnHt!: string
    pavAg!: string
    pavDp!: string
    strLn!: number
    lrHalf!: number
    painting!: string
    proportion!: string
    paintComm!: string
    keytoSymbols!: string
    reportComments!: string
    inscription!: string
    syntheticIndicator!: string
    girdlePer!: string
    polishFeatures!: string
    symmetryFeatures!: string
    shapeDescription!: string
    reportType!: string
    sorting!: string
    basketStatus!: string
    documentNo!: string
    prefix!: string
    otherReportNumber!: string
    numberStones!: string
    description!: string
    reportTypeI!: string
    reportFormatI!: string
    reportTypeII!: string
    reportFormatII!: string
    commentsConsultation!: string
    specialComments!: string
    faxComments!: string
    recheck!: string
    emailTransitOurRef!: string
    done!: string
    potentialClarity!: string
    weightlossClarity!: string
    eCG!: string
    diamLWMinmm!: string
    diamLWMaxmm!: string
    heightCAvgmm!: string
    crownPer!: string
    pavillionPer!: string
    hna!: string
    potentialMake!: string
    remarks!: string
    premiumIdealCut!: string
    diamondType!: string
    action!: string
    isRepaired: boolean

    constructor() {
        this.isRepaired = false;
    }
}